name: Release PHP Docker Image

on:
  release:
    types: [ published ]

env:
  DOCKERHUB_REPO: samtangsw/php

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate Git Version Hash
        run: echo GIT_HASH=`git rev-parse HEAD` >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: |
            ${{ env.DOCKERHUB_REPO }}:7.3-fpm
            ${{ env.DOCKERHUB_REPO }}:7.3.13-fpm
            ${{ env.DOCKERHUB_REPO }}:7.3.13-fpm-${{ env.GIT_HASH }}
